package com.komin.steganobot.botapi;

public enum BotState {
    INITIAL_STATE,
    MAIN_MENU_STATE,
    HIDE_TEXT_IMAGE_UPLOAD_STATE,
    HIDE_TEXT_STRING_UPLOAD_STATE,
    HIDE_TEXT_RESULT_UPLOAD_STATE,
    UNPACK_TEXT_IMAGE_UPLOAD_STATE,
    UNPACK_TEXT_RESULT_UPLOAD_STATE,
    ABOUT_INFO_STATE
}
